export const PDF_CONFIG = {
  MAX_FILE_SIZE_MB: 50,
  MAX_IMAGE_SIZE_MB: 20,
  MAX_FILES: 20,
  MAX_PAGES: 100,
  MAX_OCR_PAGES: 15,
  MAX_COMPARE_PAGES: 50,
  RENDER_SCALE: 1.5,
  THUMBNAIL_SCALE: 0.3,
  MAX_AI_TEXT_LENGTH: 30000,
  AI_CHUNK_SIZE: 4000,
  AI_CHUNK_OVERLAP: 200,
  AI_MAX_CHUNKS: 6,
  DEFAULT_MARGIN: 36, // 0.5 inch (72 points/inch)
} as const;
