import { PdfToolDefinition, PdfToolCategory } from './pdf/types';
import { PDF_CONFIG } from './pdf/config';

export const PDF_CATEGORIES: Record<
  string,
  { label: string; description: string; icon: string }
> = {
  organization: {
    label: 'Organize PDF',
    description: 'Merge, split, reorder, rotate, extract, and number pages.',
    icon: 'Layers',
  },
  optimize: {
    label: 'Optimize PDF',
    description: 'Compress file size, repair structure, and perform OCR / scanning.',
    icon: 'Zap',
  },
  convert_to: {
    label: 'Convert to PDF',
    description: 'Transform images, Word, PowerPoint, Excel, and HTML into standardized PDFs.',
    icon: 'FileUp',
  },
  convert_from: {
    label: 'Convert from PDF',
    description: 'Export PDF content to images, Office documents, PDF/A, and Markdown.',
    icon: 'FileDown',
  },
  editing: {
    label: 'Edit PDF',
    description: 'Annotate, watermark, visually sign, and crop PDF pages.',
    icon: 'Edit3',
  },
  security: {
    label: 'PDF Security',
    description: 'Protect with passwords, unlock documents, and permanently redact sensitive data.',
    icon: 'ShieldCheck',
  },
  forms: {
    label: 'PDF Forms',
    description: 'Inspect form field structures and fill out interactive PDF AcroForms.',
    icon: 'CheckSquare',
  },
  analysis: {
    label: 'PDF Analysis',
    description: 'Compare revisions, inspect document metadata, and extract plain text.',
    icon: 'Search',
  },
  ai: {
    label: 'AI PDF',
    description: 'Summarize documents, chat with PDFs, generate study guides, and translate content.',
    icon: 'Sparkles',
  },
};

// Aliases map for backwards-compatibility
export const SLUG_ALIASES: Record<string, string> = {
  merge: 'merge-pdf',
  split: 'split-pdf',
  organize: 'organize-pdf',
  rotate: 'rotate-pdf',
  compress: 'compress-pdf',
  repair: 'repair-pdf',
  ocr: 'ocr-pdf',
  scan: 'scan-to-pdf',
  'pdf-a': 'pdf-to-pdfa',
  edit: 'edit-pdf',
  watermark: 'watermark-pdf',
  sign: 'sign-pdf',
  crop: 'crop-pdf',
  protect: 'protect-pdf',
  unlock: 'unlock-pdf',
  redact: 'redact-pdf',
  forms: 'fill-pdf',
  compare: 'compare-pdf',
  'pdf-summary': 'ai-pdf-summary',
  'pdf-chat': 'ai-pdf-chat',
};

export const PDF_TOOLS_REGISTRY: PdfToolDefinition[] = [
  // ============================================================================
  // SECTION 1 — ORGANIZE PDF (7 Tools)
  // ============================================================================
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    category: 'organization',
    description: 'Combine multiple PDF files into one clean document in your preferred sequence.',
    icon: 'Layers',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Merges up to 20 files and 100 pages per operation in browser memory.',
    privacyNote: 'Files are merged locally in browser memory with zero server upload.',
    seoTitle: 'Merge PDF Online — Combine Multiple PDFs into One Document',
    seoDescription: 'Combine multiple PDF files into one organized document right in your browser.',
    tags: ['merge', 'combine', 'join', 'pdf', 'organize'],
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    name: 'Split PDF',
    category: 'organization',
    description: 'Separate selected pages or extract custom page ranges into new PDF files.',
    icon: 'Scissors',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', '.zip'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Supports custom comma-separated page ranges (e.g. 1-3, 5). Multi-file output is zipped.',
    privacyNote: 'Document splitting occurs locally inside your browser memory.',
    seoTitle: 'Split PDF Online — Separate and Extract Pages from PDF',
    seoDescription: 'Split PDF documents by page range or extract individual pages instantly in your browser.',
    tags: ['split', 'separate', 'extract', 'pages', 'pdf'],
  },
  {
    id: 'organize-pdf',
    slug: 'organize-pdf',
    name: 'Organize PDF',
    category: 'organization',
    description: 'Visual thumbnail workspace to reorder, duplicate, rotate, and delete pages.',
    icon: 'Layers',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Renders page thumbnails locally for interactive reordering.',
    privacyNote: '100% client-side. Your document structure stays private.',
    seoTitle: 'Organize PDF Online — Reorder, Rotate and Delete PDF Pages',
    seoDescription: 'Visually sort, reorder, rotate, and delete PDF pages with an intuitive workspace.',
    tags: ['organize', 'reorder', 'sort', 'pages', 'pdf'],
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    name: 'Remove Pages',
    category: 'organization',
    description: 'Delete unwanted or blank pages permanently from your PDF document.',
    icon: 'Trash2',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Permanently eliminates page dictionaries and references from exported PDF.',
    privacyNote: 'Selected pages are purged directly in browser memory.',
    seoTitle: 'Remove Pages from PDF — Delete PDF Pages Online',
    seoDescription: 'Delete specific pages from any PDF document with instant browser processing.',
    tags: ['remove', 'delete', 'cut', 'pages', 'pdf'],
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    name: 'Extract Pages',
    category: 'organization',
    description: 'Create a new lightweight PDF containing only your selected pages.',
    icon: 'FileDown',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Select individual pages or ranges to export into a standalone PDF.',
    privacyNote: 'Extracted pages are compiled locally.',
    seoTitle: 'Extract Pages from PDF — Save Selected Pages as New PDF',
    seoDescription: 'Extract specific pages from your PDF and download them as a new file.',
    tags: ['extract', 'pages', 'select', 'pdf', 'save'],
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'organization',
    description: 'Rotate upside-down or sideways pages clockwise or counterclockwise.',
    icon: 'RotateCw',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Rotates in standard 90°, 180°, and 270° increments.',
    privacyNote: 'Orientation transformations execute entirely client-side.',
    seoTitle: 'Rotate PDF Online — Permanently Rotate PDF Pages',
    seoDescription: 'Rotate PDF pages permanently to portrait or landscape orientation.',
    tags: ['rotate', 'orientation', 'landscape', 'portrait', 'pdf'],
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    category: 'organization',
    description: 'Stamp page numbering across your document with custom position and font.',
    icon: 'Hash',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Supports header and footer placement (left, center, right) and "Page X of Y" formatting.',
    privacyNote: 'Page number stamping executes client-side.',
    seoTitle: 'Add Page Numbers to PDF Online — Header and Footer Numbering',
    seoDescription: 'Stamp page numbers onto PDF documents with custom styling and placement.',
    tags: ['page numbers', 'numbering', 'footer', 'header', 'pdf'],
  },

  // ============================================================================
  // SECTION 2 — OPTIMIZE PDF (4 Tools)
  // ============================================================================
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    category: 'optimize',
    description: 'Reduce PDF file size while preserving practical readability and layout.',
    icon: 'Minimize2',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Optimizes content streams and compresses embedded canvas images. Discloses true byte metrics; never claims reduction if file size increases.',
    privacyNote: 'Compression happens 100% in your browser.',
    seoTitle: 'Compress PDF Online — Reduce PDF File Size',
    seoDescription: 'Shrink PDF file size for easier sharing while keeping text sharp and readable.',
    tags: ['compress', 'shrink', 'reduce size', 'optimize', 'pdf'],
  },
  {
    id: 'repair-pdf',
    slug: 'repair-pdf',
    name: 'Repair PDF',
    category: 'optimize',
    description: 'Attempt structural recovery on damaged or unreadable PDF files.',
    icon: 'Wrench',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'LIMITED MODE: Reconstructs broken cross-reference tables and recovers uncorrupted page streams. Files with completely corrupted magic headers or encrypted damage may be unrecoverable.',
    privacyNote: 'Rebuilding occurs strictly in browser memory.',
    seoTitle: 'Repair PDF Online — Fix Damaged and Corrupted PDFs',
    seoDescription: 'Attempt recovery of corrupted PDF documents by reconstructing xref tables and stream dictionaries.',
    tags: ['repair', 'fix', 'corrupted', 'recover', 'pdf'],
  },
  {
    id: 'ocr-pdf',
    slug: 'ocr-pdf',
    name: 'OCR PDF',
    category: 'optimize',
    description: 'Extract text from scanned PDF pages and images using optical character recognition.',
    icon: 'ScanText',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.pdf'],
    maxFileSizeMB: 30,
    maxPages: 25,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Rasterizes PDF pages via HTML5 Canvas and processes OCR via Tesseract.js Web Workers. Memory-managed sequentially.',
    privacyNote: 'OCR runs inside client Web Workers. Your scans are never sent to external OCR cloud servers.',
    seoTitle: 'OCR PDF Online — Convert Scanned PDFs into Searchable Text',
    seoDescription: 'Extract text from scanned PDFs and images using private client-side OCR.',
    tags: ['ocr', 'scan', 'text recognition', 'searchable', 'pdf'],
  },
  {
    id: 'scan-to-pdf',
    slug: 'scan-to-pdf',
    name: 'Scan to PDF',
    category: 'optimize',
    description: 'Capture physical documents using your device camera and save as PDF.',
    icon: 'Camera',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['image/*', 'video/*'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: 25,
    maxPages: 20,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Requires device camera permission. Automatically crops and embeds captured snaps into standard A4 PDF pages.',
    privacyNote: 'Camera feed is processed live on-device. Images never leave your browser.',
    seoTitle: 'Scan to PDF — Digitize Documents with Device Camera',
    seoDescription: 'Use your phone or laptop webcam to scan physical notes, receipts, and assignments into PDF.',
    tags: ['scan', 'camera', 'photo to pdf', 'digitize', 'mobile'],
  },

  // ============================================================================
  // SECTION 3 — CONVERT TO PDF (6 Tools)
  // ============================================================================
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    category: 'convert_to',
    description: 'Convert JPG photos and images into standardized, high-quality PDF documents.',
    icon: 'Image',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.jpg', '.jpeg', 'image/jpeg'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 50,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Supports batch image selection, orientation auto-fitting, and custom margins.',
    privacyNote: 'Images are packed into PDF binary in browser memory.',
    seoTitle: 'JPG to PDF Converter — Convert JPG Images to PDF Online',
    seoDescription: 'Convert JPG pictures into a clean PDF document in seconds with complete privacy.',
    tags: ['jpg', 'jpeg', 'image to pdf', 'photos', 'convert'],
  },
  {
    id: 'png-to-pdf',
    slug: 'png-to-pdf',
    name: 'PNG to PDF',
    category: 'convert_to',
    description: 'Convert PNG graphics and transparent screenshots into clean PDF pages.',
    icon: 'FileImage',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.png', 'image/png'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 50,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Preserves image alpha transparency and pixel sharpness.',
    privacyNote: 'Processed entirely client-side.',
    seoTitle: 'PNG to PDF Converter — Convert Transparent PNGs to PDF',
    seoDescription: 'Convert PNG graphics and diagrams into PDF pages right in your browser.',
    tags: ['png', 'image to pdf', 'screenshots', 'graphics', 'convert'],
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'convert_to',
    description: 'Convert Microsoft Word (.docx) documents into standardized PDF files.',
    icon: 'FileText',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: 25,
    maxPages: 50,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Parses OpenXML word processing XML trees into structured PDF layout.',
    privacyNote: 'Documents are converted locally in browser memory.',
    seoTitle: 'Word to PDF Converter — Convert DOCX to PDF Online',
    seoDescription: 'Convert Microsoft Word DOCX files into PDF documents privately in your browser.',
    tags: ['word', 'docx', 'document', 'convert', 'pdf'],
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    category: 'convert_to',
    description: 'Convert PowerPoint (.pptx) presentations into slide-by-slide PDF handouts.',
    icon: 'Presentation',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pptx', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: 30,
    maxPages: 40,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Extracts slide titles, body bullet points, and speaker notes into landscape PDF pages.',
    privacyNote: 'Slides are processed client-side.',
    seoTitle: 'PowerPoint to PDF Converter — Convert PPTX to PDF Online',
    seoDescription: 'Turn PowerPoint presentation decks into readable PDF slide documents.',
    tags: ['powerpoint', 'pptx', 'presentation', 'slides', 'convert'],
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    category: 'convert_to',
    description: 'Convert Excel (.xlsx) spreadsheets and tables into clean printable PDF reports.',
    icon: 'Table',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: 20,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Parses shared strings and worksheet cell values into formatted tabular PDF grids.',
    privacyNote: 'Spreadsheet formulas and values remain inside browser memory.',
    seoTitle: 'Excel to PDF Converter — Convert XLSX Sheets to PDF',
    seoDescription: 'Convert Excel spreadsheets into tabular PDF reports with clean page pagination.',
    tags: ['excel', 'xlsx', 'spreadsheet', 'sheets', 'tables', 'convert'],
  },
  {
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    category: 'convert_to',
    description: 'Render semantic HTML code or rich formatted notes directly into PDF.',
    icon: 'Code',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.html', '.htm', 'text/html', 'text/plain'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: 15,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Renders semantic HTML tags (h1-h6, p, ul, ol, table, code) with CSS typography into multi-page PDF.',
    privacyNote: 'HTML parsing and rendering executes locally in your browser.',
    seoTitle: 'HTML to PDF Converter — Convert Web Code to PDF Online',
    seoDescription: 'Convert HTML code and web text into clean multi-page PDF documents.',
    tags: ['html', 'web', 'code to pdf', 'convert', 'format'],
  },

  // ============================================================================
  // SECTION 4 — CONVERT FROM PDF (7 Tools)
  // ============================================================================
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    category: 'convert_from',
    description: 'Extract PDF pages as high-resolution JPG images packaged in a zip archive.',
    icon: 'Image',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.jpg', '.zip'],
    maxFileSizeMB: 30,
    maxPages: 25,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Rasterizes pages to canvas at 1.5x scale and exports as JPEG.',
    privacyNote: '100% in-browser rendering via pdfjs-dist.',
    seoTitle: 'PDF to JPG Converter — Export PDF Pages as Images Online',
    seoDescription: 'Convert PDF pages into crisp JPG images right in your browser.',
    tags: ['pdf to jpg', 'pdf to image', 'convert', 'extract images', 'export'],
  },
  {
    id: 'pdf-to-png',
    slug: 'pdf-to-png',
    name: 'PDF to PNG',
    category: 'convert_from',
    description: 'Export PDF pages as lossless PNG images for high-definition diagrams.',
    icon: 'FileImage',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.png', '.zip'],
    maxFileSizeMB: 30,
    maxPages: 25,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Lossless rendering for architectural charts, formulas, and schematics.',
    privacyNote: 'Rendered locally using canvas.',
    seoTitle: 'PDF to PNG Converter — Lossless Image Extraction from PDF',
    seoDescription: 'Convert PDF document pages into high-definition PNG images.',
    tags: ['pdf to png', 'lossless', 'images', 'diagrams', 'export'],
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'convert_from',
    description: 'Reconstruct PDF text and headings into an editable Microsoft Word (.docx) file.',
    icon: 'FileText',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    maxFileSizeMB: 25,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Generates valid OpenXML DOCX archive with extracted paragraph hierarchy and font styles.',
    privacyNote: 'DOCX file is assembled locally using JSZip.',
    seoTitle: 'PDF to Word Converter — Convert PDF to Editable DOCX',
    seoDescription: 'Extract and convert PDF text and structure into an editable Microsoft Word document.',
    tags: ['pdf to word', 'docx', 'convert', 'editable', 'extract'],
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    category: 'convert_from',
    description: 'Convert PDF presentation slides into an editable PowerPoint (.pptx) deck.',
    icon: 'Presentation',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pptx', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'],
    maxFileSizeMB: 25,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Constructs valid OpenXML presentation decks with extracted slide titles and bullet items.',
    privacyNote: 'Generated client-side in browser memory.',
    seoTitle: 'PDF to PowerPoint Converter — Convert PDF to PPTX Slides',
    seoDescription: 'Convert PDF documents into editable Microsoft PowerPoint presentation decks.',
    tags: ['pdf to pptx', 'powerpoint', 'presentation', 'slides', 'convert'],
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    category: 'convert_from',
    description: 'Extract structured tabular data from PDF pages into an Excel (.xlsx) spreadsheet.',
    icon: 'Table',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    maxFileSizeMB: 20,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Parses spatial text coordinates into tabular rows and columns inside valid OpenXML workbook.',
    privacyNote: 'Workbook generated client-side.',
    seoTitle: 'PDF to Excel Converter — Extract Tables to XLSX Spreadsheet',
    seoDescription: 'Extract tables and numerical data from PDF documents into Excel spreadsheets.',
    tags: ['pdf to excel', 'xlsx', 'tables', 'spreadsheet', 'convert'],
  },
  {
    id: 'pdf-to-pdfa',
    slug: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    category: 'convert_from',
    description: 'Prepare documents for long-term digital preservation and archival compliance.',
    icon: 'Archive',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'PDF/A METADATA PREPARATION: Embeds ISO PDF/A-1b metadata schemas and uncompressed objects. Official ISO certification requires external formal preflight validation.',
    privacyNote: 'Document metadata is updated locally.',
    seoTitle: 'PDF to PDF/A Converter — Archival Preparation Online',
    seoDescription: 'Embed standardized PDF/A-1b metadata schema into your PDF documents for long-term archiving.',
    tags: ['pdf/a', 'archive', 'compliance', 'iso', 'preservation'],
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    category: 'convert_from',
    description: 'Convert PDF documents into clean, structured Markdown (.md) with headings and lists.',
    icon: 'FileCode2',
    status: 'PRODUCTION',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.md', 'text/markdown'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 40,
    requiresAI: true,
    requiresServer: true,
    badge: 'AI Powered',
    limitations: 'Extracts text structure and leverages AI synthesis for clean markdown formatting.',
    privacyNote: 'Text structure is processed via the AI gateway. Subject to AI kill switch.',
    seoTitle: 'PDF to Markdown Converter — Convert PDF to MD Online',
    seoDescription: 'Convert PDF documents into formatted Markdown files with preserved headings and lists.',
    tags: ['markdown', 'md', 'convert', 'notes', 'obsidian', 'notion', 'pdf'],
  },

  // ============================================================================
  // SECTION 5 — EDIT PDF (4 Tools)
  // ============================================================================
  {
    id: 'edit-pdf',
    slug: 'edit-pdf',
    name: 'Edit PDF',
    category: 'editing',
    description: 'Add text notes, highlights, shapes, and arrows directly onto PDF pages.',
    icon: 'Pencil',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Interactive canvas overlay stamps text, highlights, and annotations permanently into PDF content streams.',
    privacyNote: 'All editing operations execute inside your browser canvas.',
    seoTitle: 'Edit PDF Online — Annotate and Add Text to PDF',
    seoDescription: 'Add text annotations, freehand notes, and shapes to any PDF document.',
    tags: ['edit', 'annotate', 'text', 'notes', 'pdf'],
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark-pdf',
    name: 'Watermark PDF',
    category: 'editing',
    description: 'Stamp customized text or logo watermarks across all pages with opacity control.',
    icon: 'Stamp',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Supports 45° diagonal angle, custom opacity, and font sizing across all pages.',
    privacyNote: 'Watermarking runs entirely on-device.',
    seoTitle: 'Watermark PDF Online — Add Text and Logo Watermarks to PDF',
    seoDescription: 'Protect your assignments and drafts with custom diagonal text or image watermarks.',
    tags: ['watermark', 'stamp', 'confidential', 'draft', 'pdf'],
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    name: 'Sign PDF',
    category: 'editing',
    description: 'Draw or insert a visual signature and place it anywhere on your document.',
    icon: 'PenTool',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'VISUAL SIGNATURE INSERTION: Stamps a drawn or uploaded visual signature onto document pages. Does not generate cryptographic X.509 PKI digital certificates.',
    privacyNote: 'Signatures are drawn in browser memory and embedded directly into PDF bytes.',
    seoTitle: 'Sign PDF Online — Add Visual Signature to PDF Documents',
    seoDescription: 'Draw and place your personal signature onto PDF contracts, forms, and permission slips.',
    tags: ['sign', 'signature', 'draw signature', 'autograph', 'pdf'],
  },
  {
    id: 'crop-pdf',
    slug: 'crop-pdf',
    name: 'Crop PDF',
    category: 'editing',
    description: 'Trim margins and remove unwanted outer whitespace across selected pages.',
    icon: 'Crop',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Modifies the PDF MediaBox and CropBox bounding coordinates.',
    privacyNote: 'Crop coordinates are applied client-side.',
    seoTitle: 'Crop PDF Online — Trim Margins and Whitespace from PDF',
    seoDescription: 'Trim unwanted white margins and crop PDF pages for cleaner printing and reading.',
    tags: ['crop', 'trim', 'margins', 'whitespace', 'pdf'],
  },

  // ============================================================================
  // SECTION 6 — PDF SECURITY (3 Tools)
  // ============================================================================
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    name: 'Protect PDF',
    category: 'security',
    description: 'Apply document protection and security flags to restrict unauthorized usage.',
    icon: 'Lock',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'LIMITED PROTECTION: Pure in-browser JavaScript lacks proprietary Adobe crypt filters for AES-256 standard encryption. Applies security metadata restrictions only. For high-security AES-256 encryption, use native desktop software.',
    privacyNote: 'Metadata is updated in local browser memory.',
    seoTitle: 'Protect PDF Online — Password & Security Restrictions for PDF',
    seoDescription: 'Apply security restrictions and password protection to PDF documents.',
    tags: ['protect', 'password', 'encrypt', 'security', 'pdf'],
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    category: 'security',
    description: 'Remove password protection from documents where you possess the valid password.',
    icon: 'Unlock',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Requires the authorized document password to decrypt and export an unencrypted version. Does not bypass or crack unknown passwords.',
    privacyNote: 'Passwords are used strictly in browser memory to decrypt the PDF stream.',
    seoTitle: 'Unlock PDF Online — Remove Security Restrictions with Password',
    seoDescription: 'Decrypt and remove password security from your PDF documents.',
    tags: ['unlock', 'decrypt', 'remove password', 'security', 'pdf'],
  },
  {
    id: 'redact-pdf',
    slug: 'redact-pdf',
    name: 'Redact PDF',
    category: 'security',
    description: 'Permanently remove and black out confidential text and sensitive numbers.',
    icon: 'EyeOff',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: 25,
    maxPages: 25,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'PERMANENT FLATTENING: Redacted areas are painted with opaque black masks and flattened to raster images, permanently destroying underlying text streams.',
    privacyNote: 'Redaction executes entirely inside your browser canvas.',
    seoTitle: 'Redact PDF Online — Permanently Black Out Sensitive Information',
    seoDescription: 'Permanently black out and purge confidential data, grades, and personal identifiers from PDF.',
    tags: ['redact', 'blackout', 'privacy', 'confidential', 'sanitize', 'pdf'],
  },

  // ============================================================================
  // SECTION 7 — PDF FORMS (2 Tools)
  // ============================================================================
  {
    id: 'pdf-forms',
    slug: 'pdf-forms',
    name: 'PDF Forms',
    category: 'forms',
    description: 'Inspect, validate, and analyze interactive AcroForm fields inside PDF documents.',
    icon: 'CheckSquare',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Detects text boxes, checkboxes, radio buttons, and dropdown options defined in the document.',
    privacyNote: 'Form structure analysis occurs client-side.',
    seoTitle: 'PDF Forms — Inspect and Analyze Interactive Form Fields',
    seoDescription: 'Inspect AcroForm field definitions and interactive properties in any PDF.',
    tags: ['forms', 'acroforms', 'fields', 'interactive', 'pdf'],
  },
  {
    id: 'fill-pdf',
    slug: 'fill-pdf',
    name: 'Fill PDF Forms',
    category: 'forms',
    description: 'Type into interactive form fields, check boxes, and export filled documents.',
    icon: 'CheckSquare',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Supports interactive input for text fields, checkboxes, and select dropdowns, with optional appearance flattening.',
    privacyNote: 'Filled form data is processed in browser memory and not transmitted to servers.',
    seoTitle: 'Fill PDF Forms Online — Type and Complete Interactive Forms',
    seoDescription: 'Fill out interactive PDF applications, forms, and surveys directly in your browser.',
    tags: ['fill forms', 'complete form', 'acroforms', 'inputs', 'pdf'],
  },

  // ============================================================================
  // SECTION 8 — PDF ANALYSIS (3 Tools)
  // ============================================================================
  {
    id: 'compare-pdf',
    slug: 'compare-pdf',
    name: 'Compare PDF',
    category: 'analysis',
    description: 'Compare two revisions of a PDF and highlight text differences side-by-side.',
    icon: 'GitCompare',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.pdf'],
    maxFileSizeMB: 25,
    maxPages: 25,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Performs word-level and line-level diff comparison across extracted page streams.',
    privacyNote: 'Comparison logic executes locally in browser memory.',
    seoTitle: 'Compare PDF Online — Side-by-Side Document Diff Comparison',
    seoDescription: 'Compare two versions of a PDF document to find changes, edits, and revisions.',
    tags: ['compare', 'diff', 'revisions', 'differences', 'pdf'],
  },
  {
    id: 'pdf-info',
    slug: 'pdf-info',
    name: 'PDF Information',
    category: 'analysis',
    description: 'Inspect PDF metadata, producer, creator, version, page counts, and dimensions.',
    icon: 'Search',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Extracts title, author, subject, keywords, producer, creator, creation date, modification date, and page count.',
    privacyNote: 'Metadata inspection is 100% client-side.',
    seoTitle: 'PDF Information & Metadata Viewer — Inspect PDF Properties',
    seoDescription: 'View document metadata, dimensions, author, version, and page counts in any PDF.',
    tags: ['info', 'metadata', 'properties', 'producer', 'page count', 'pdf'],
  },
  {
    id: 'pdf-text',
    slug: 'pdf-text',
    name: 'PDF Text Extractor',
    category: 'analysis',
    description: 'Extract raw plain text from all pages with one click for easy copying or search.',
    icon: 'FileText',
    status: 'PRODUCTION',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.txt'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Extracts raw text streams across up to 100 pages using pdfjs-dist.',
    privacyNote: 'Extracted text is processed locally and never stored on a server.',
    seoTitle: 'PDF Text Extractor — Extract Plain Text from PDF Online',
    seoDescription: 'Extract plain text from your PDF files instantly for easy editing, copying, and search.',
    tags: ['text extractor', 'plain text', 'copy text', 'extract', 'pdf'],
  },

  // ============================================================================
  // SECTION 9 — AI PDF (4 Tools)
  // ============================================================================
  {
    id: 'ai-pdf-summary',
    slug: 'ai-pdf-summary',
    name: 'AI PDF Summary',
    category: 'ai',
    description: 'Generate concise executive summaries, key takeaways, and definitions from PDFs.',
    icon: 'Sparkles',
    status: 'PRODUCTION',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: true,
    requiresServer: true,
    isPopular: true,
    badge: 'AI Powered',
    limitations: 'Chunks document text and generates structured summaries via the AI gateway. Subject to the Global AI kill switch.',
    privacyNote: 'Document chunks are processed through server-side AI gateway without permanent storage.',
    seoTitle: 'AI PDF Summary — Summarize Academic Papers & PDF Notes',
    seoDescription: 'Condense long textbooks and study materials into structured bullet summaries with AI.',
    tags: ['ai summary', 'summarize', 'notes', 'study', 'pdf'],
  },
  {
    id: 'ai-pdf-chat',
    slug: 'ai-pdf-chat',
    name: 'AI PDF Chat',
    category: 'ai',
    description: 'Ask questions, clarify complex theorems, and explore your document with AI.',
    icon: 'Bot',
    status: 'PRODUCTION',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: true,
    requiresServer: true,
    isPopular: true,
    badge: 'AI Powered',
    limitations: 'Answers user questions based on relevant extracted chunks from the active document.',
    privacyNote: 'Chunks are evaluated in transient memory during your conversation session.',
    seoTitle: 'AI PDF Chat — Conversational Q&A with Your Documents',
    seoDescription: 'Chat interactively with any PDF document to ask questions and clarify concepts.',
    tags: ['ai chat', 'chat with pdf', 'document qa', 'study', 'pdf'],
  },
  {
    id: 'ai-study-guide',
    slug: 'ai-study-guide',
    name: 'AI Study Guide',
    category: 'ai',
    description: 'Transform any lecture notes or textbook chapter into a structured revision guide.',
    icon: 'Sparkles',
    status: 'PRODUCTION',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: true,
    requiresServer: true,
    badge: 'AI Powered',
    limitations: 'Synthesizes key concepts, memory formulas, review questions, and exam tips into a study package.',
    privacyNote: 'Extracted text is processed via the AI gateway with zero permanent storage.',
    seoTitle: 'AI Study Guide Generator — Create Exam Revision Sheets from PDF',
    seoDescription: 'Turn textbook chapters and lecture PDFs into comprehensive exam study guides.',
    tags: ['study guide', 'exam prep', 'revision', 'flashcards', 'ai', 'pdf'],
  },
  {
    id: 'translate-pdf',
    slug: 'translate-pdf',
    name: 'Translate PDF',
    category: 'ai',
    description: 'Translate research papers and PDF documents into multiple global languages.',
    icon: 'Languages',
    status: 'PRODUCTION',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: true,
    requiresServer: true,
    badge: 'AI Powered',
    limitations: 'Translates extracted text sections via the AI gateway into clean translated documents.',
    privacyNote: 'Sends extracted text to the AI gateway. Subject to the Global AI kill switch.',
    seoTitle: 'Translate PDF Online — AI Document Translator',
    seoDescription: 'Translate academic papers and PDFs into multiple languages accurately with AI.',
    tags: ['translate', 'languages', 'multilingual', 'ai', 'pdf'],
  },
];

/**
 * Retrieves a PDF tool definition by its unique slug or recognized legacy alias.
 */
export function getPdfToolBySlug(slug: string): PdfToolDefinition | undefined {
  const normalized = (slug || '').trim().toLowerCase();
  const canonicalSlug = SLUG_ALIASES[normalized] || normalized;
  return PDF_TOOLS_REGISTRY.find((t) => t.slug === canonicalSlug || t.id === canonicalSlug);
}

/**
 * Returns all valid PDF tool slugs (including legacy aliases for static generation and routing).
 */
export function getAllPdfToolSlugs(): string[] {
  const canonical = PDF_TOOLS_REGISTRY.map((t) => t.slug);
  const aliases = Object.keys(SLUG_ALIASES);
  return Array.from(new Set([...canonical, ...aliases]));
}

/**
 * Returns PDF tools filtered by category.
 */
export function getPdfToolsByCategory(category: string): PdfToolDefinition[] {
  return PDF_TOOLS_REGISTRY.filter((t) => t.category === category);
}
