import { PdfToolDefinition, PdfToolCategory } from './pdf/types';
import { PDF_CONFIG } from './pdf/config';

export const PDF_CATEGORIES: Record<
  PdfToolCategory,
  { label: string; description: string; icon: string }
> = {
  organization: {
    label: 'Organize',
    description: 'Merge, split, reorder, rotate, and manage pages in your PDFs.',
    icon: 'Layers',
  },
  conversion: {
    label: 'Convert',
    description: 'Convert PDFs to and from images, documents, and standard formats.',
    icon: 'ArrowLeftRight',
  },
  editing: {
    label: 'Edit',
    description: 'Annotate, sign, watermark, crop, redact, and fill PDF forms.',
    icon: 'Edit3',
  },
  optimization: {
    label: 'Optimize',
    description: 'Reduce file size and attempt safe document structural repairs.',
    icon: 'Zap',
  },
  security: {
    label: 'Security',
    description: 'Protect with passwords, unlock documents, and compare revisions.',
    icon: 'ShieldCheck',
  },
  scanning: {
    label: 'Scan & OCR',
    description: 'Digitize physical papers with your camera and extract text via OCR.',
    icon: 'Scan',
  },
  ai: {
    label: 'AI PDF',
    description: 'Summarize study materials, translate documents, and convert to Markdown.',
    icon: 'Sparkles',
  },
};

export const PDF_TOOLS_REGISTRY: PdfToolDefinition[] = [
  // 1. PDF Organization (7 tools)
  {
    id: 'merge-pdf',
    slug: 'merge',
    name: 'Merge PDF',
    category: 'organization',
    description: 'Combine multiple PDF documents into a single organized file in your preferred order.',
    icon: 'Merge',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', 'application/pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Merges up to 20 files and 100 pages per operation in browser memory.',
    privacyNote: 'Files are merged directly in your browser without uploading to any server.',
    seoTitle: 'Merge PDF Online — Combine Multiple PDFs into One Document Free',
    seoDescription: 'Merge and combine multiple PDF files into one complete document right in your browser. 100% private, free, and fast.',
    tags: ['merge', 'combine', 'join', 'pdf', 'organize'],
  },
  {
    id: 'split-pdf',
    slug: 'split',
    name: 'Split PDF',
    category: 'organization',
    description: 'Extract specific page ranges or split every page into separate PDF documents.',
    icon: 'Scissors',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf', '.zip'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Supports custom comma-separated page ranges (e.g. 1-3, 5). Multi-file output is zipped.',
    privacyNote: 'Document splitting occurs locally inside your browser memory.',
    seoTitle: 'Split PDF Online — Separate and Extract Pages from PDF Free',
    seoDescription: 'Split PDF documents by page range or extract individual pages instantly in your browser.',
    tags: ['split', 'separate', 'extract', 'pages', 'pdf'],
  },
  {
    id: 'organize-pdf',
    slug: 'organize',
    name: 'Organize PDF',
    category: 'organization',
    description: 'Visual thumbnail workspace to reorder, duplicate, rotate, and delete pages with drag & drop.',
    icon: 'Layers',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Renders page thumbnails locally for interactive reordering.',
    privacyNote: '100% client-side. Your document structure stays private.',
    seoTitle: 'Organize PDF Online — Reorder, Rotate and Delete PDF Pages Free',
    seoDescription: 'Visually sort, reorder, rotate, and delete PDF pages with an intuitive drag-and-drop workspace.',
    tags: ['organize', 'reorder', 'sort', 'pages', 'pdf'],
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    name: 'Remove Pages',
    category: 'organization',
    description: 'Select unwanted pages from your document and delete them permanently from the exported PDF.',
    icon: 'Trash2',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Must retain at least one page in the exported document.',
    privacyNote: 'Executed entirely in browser memory.',
    seoTitle: 'Remove Pages from PDF Online Free | StudentAI',
    seoDescription: 'Delete unnecessary or blank pages from your PDF documents easily with visual page selection.',
    tags: ['remove', 'delete', 'pages', 'pdf', 'clean'],
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    name: 'Extract Pages',
    category: 'organization',
    description: 'Select important pages from a large document and save them into a compact new PDF.',
    icon: 'FileDown',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Extracts chosen pages while preserving internal page vector streams and fonts.',
    privacyNote: 'No server upload required.',
    seoTitle: 'Extract Pages from PDF Online Free | StudentAI',
    seoDescription: 'Extract specific pages or sections from any PDF document into a new lightweight PDF file.',
    tags: ['extract', 'save', 'pages', 'pdf', 'export'],
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate',
    name: 'Rotate PDF',
    category: 'organization',
    description: 'Fix upside-down or sideways pages. Rotate 90°, 180°, or 270° clockwise or counter-clockwise.',
    icon: 'RotateCw',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Permanently updates page orientation dictionaries in the output PDF.',
    privacyNote: 'Processed locally in browser.',
    seoTitle: 'Rotate PDF Online — Change PDF Page Orientation Free',
    seoDescription: 'Rotate PDF pages permanently to landscape or portrait in seconds. Free and client-side.',
    tags: ['rotate', 'orientation', 'landscape', 'portrait', 'pdf'],
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    name: 'Add Page Numbers',
    category: 'organization',
    description: 'Insert customizable page numbers into the header or footer of your PDF with custom position and font sizing.',
    icon: 'Hash',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Supports top/bottom, left/center/right alignment and starting index offsets.',
    privacyNote: 'Rendered in browser memory.',
    seoTitle: 'Add Page Numbers to PDF Online Free | StudentAI',
    seoDescription: 'Number PDF pages with customizable positions, formatting, and font sizing without server uploads.',
    tags: ['page numbers', 'header', 'footer', 'numbering', 'pdf'],
  },

  // 2. PDF Conversion (10 tools)
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF → Word (.docx)',
    category: 'conversion',
    description: 'Extract text, headings, and structure into an editable Microsoft Word (.docx) document.',
    icon: 'FileText',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.docx'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 50,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Produces a genuine OpenXML .docx file with extracted paragraphs and headings. Complex multi-column magazine layouts are simplified.',
    privacyNote: 'Generated client-side. No document text leaves your machine.',
    seoTitle: 'PDF to Word Converter — Convert PDF to Editable DOCX Free',
    seoDescription: 'Convert PDF documents into editable Word .docx files locally in your browser. Free, secure, and instant.',
    tags: ['pdf to word', 'docx', 'convert', 'editable', 'document'],
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    name: 'PDF → PowerPoint (.pptx)',
    category: 'conversion',
    description: 'Convert PDF lecture notes or presentation slides into editable Microsoft PowerPoint (.pptx) slides.',
    icon: 'Presentation',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pptx'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 40,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Creates genuine OpenXML .pptx presentation slides with extracted slide titles and text boxes.',
    privacyNote: 'Processed 100% in browser memory.',
    seoTitle: 'PDF to PowerPoint Converter — Convert PDF to PPTX Free',
    seoDescription: 'Transform PDF handouts and slides into editable PowerPoint presentations online.',
    tags: ['pdf to pptx', 'powerpoint', 'slides', 'presentation', 'convert'],
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    name: 'PDF → Excel (.xlsx)',
    category: 'conversion',
    description: 'Extract tables, tabular data, and numerical columns from PDF into a structured Excel (.xlsx) workbook.',
    icon: 'Table',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.xlsx', '.csv'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Detects structured grid rows and columns. Complex nested visual tables may require manual adjustment.',
    privacyNote: 'Extracted directly in browser memory.',
    seoTitle: 'PDF to Excel Converter — Extract PDF Tables to XLSX Free',
    seoDescription: 'Extract financial tables, grade sheets, and structured data from PDF into Microsoft Excel workbooks.',
    tags: ['pdf to excel', 'xlsx', 'spreadsheet', 'tables', 'convert'],
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word → PDF',
    category: 'conversion',
    description: 'Convert Word (.docx) documents into clean, portable PDF documents.',
    icon: 'FileCode',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.docx'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: 25,
    maxPages: 50,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'Parses standard paragraphs, headings, bold/italics, and lists. Complex Word macros, custom VML shapes, or SmartArt are not rendered.',
    privacyNote: 'Processed client-side in browser.',
    seoTitle: 'Word to PDF Converter Online Free | StudentAI',
    seoDescription: 'Convert Microsoft Word DOCX files into standardized PDF documents right in your browser.',
    tags: ['word to pdf', 'docx to pdf', 'convert', 'document'],
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    name: 'PowerPoint → PDF',
    category: 'conversion',
    description: 'Convert PowerPoint (.pptx) presentation outlines into readable PDF slides.',
    icon: 'Presentation',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.pptx'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: 25,
    maxPages: 40,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'Converts slide text bodies, headings, and outlines into PDF pages. Proprietary animations and 3D shapes are omitted.',
    privacyNote: 'Client-side processing.',
    seoTitle: 'PowerPoint to PDF Converter Online Free | StudentAI',
    seoDescription: 'Convert PPTX presentation files into PDF documents for easy sharing and printing.',
    tags: ['pptx to pdf', 'powerpoint to pdf', 'slides', 'convert'],
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel → PDF',
    category: 'conversion',
    description: 'Convert spreadsheet worksheets (.xlsx, .csv) into clean tabular PDF documents.',
    icon: 'Table',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.xlsx', '.csv'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: 20,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'Formats table cells into PDF grid pages with automatic column widths.',
    privacyNote: 'Spreadsheet contents remain in browser memory.',
    seoTitle: 'Excel to PDF Converter Online Free | StudentAI',
    seoDescription: 'Convert Excel spreadsheets and CSV data into organized, printable PDF tables.',
    tags: ['excel to pdf', 'xlsx to pdf', 'csv to pdf', 'convert'],
  },
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    name: 'PDF → JPG/PNG',
    category: 'conversion',
    description: 'Rasterize PDF pages into high-resolution JPG or PNG images. Download individually or as a ZIP.',
    icon: 'Image',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.jpg', '.png', '.zip'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Renders pages to HTML5 Canvas at up to 300 DPI for crisp readability.',
    privacyNote: 'Image rendering occurs on your device without server transmission.',
    seoTitle: 'PDF to JPG Converter — Convert PDF Pages to Images Free',
    seoDescription: 'Convert PDF pages into high-resolution JPG or PNG images online. Free, fast, and completely private.',
    tags: ['pdf to jpg', 'pdf to png', 'images', 'rasterize', 'convert'],
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    name: 'JPG/PNG → PDF',
    category: 'conversion',
    description: 'Assemble JPG, PNG, and WebP images into a single standardized PDF document.',
    icon: 'FileImage',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_IMAGE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_FILES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Supports custom page margins (none, small, normal) and portrait/landscape orientation.',
    privacyNote: 'Images are processed locally.',
    seoTitle: 'JPG to PDF Converter — Convert Images to PDF Online Free',
    seoDescription: 'Convert JPG, PNG, and photos into a clean PDF document in seconds. 100% free and client-side.',
    tags: ['jpg to pdf', 'png to pdf', 'images to pdf', 'photos', 'convert'],
  },
  {
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    name: 'HTML → PDF',
    category: 'conversion',
    description: 'Render clean HTML text, articles, or code snippets into formatted PDF documents.',
    icon: 'Code',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.html', '.htm', 'text/html'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: 10,
    maxPages: 20,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'Renders semantic HTML tags (H1-H6, p, ul/ol, pre/code, table). Advanced CSS Grid/Flexbox layouts should use browser print dialog for full fidelity.',
    privacyNote: 'Sandboxed HTML rendering with no remote script execution.',
    seoTitle: 'HTML to PDF Converter Online Free | StudentAI',
    seoDescription: 'Convert HTML code and web content into clean PDF documents locally in your browser.',
    tags: ['html to pdf', 'web to pdf', 'code to pdf', 'convert'],
  },
  {
    id: 'pdf-a',
    slug: 'pdf-a',
    name: 'PDF/A Preparation',
    category: 'conversion',
    description: 'Prepare your PDF for long-term archiving by embedding ISO PDF/A-1b metadata and color intent profiles.',
    icon: 'Archive',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'Embeds standard PDF/A-1b XMP metadata schemas and sRGB output intents. Does not guarantee third-party certified ISO validation.',
    privacyNote: 'Prepared locally in browser memory.',
    seoTitle: 'PDF/A Preparation Online — Archive Ready PDF Tool | StudentAI',
    seoDescription: 'Prepare documents for long-term archiving by embedding PDF/A metadata and color profiles.',
    tags: ['pdf a', 'archive', 'compliance', 'iso', 'preservation'],
  },

  // 3. PDF Editing (6 tools)
  {
    id: 'edit-pdf',
    slug: 'edit',
    name: 'Edit PDF',
    category: 'editing',
    description: 'Interactive annotation workspace to add text, draw, place rectangles, highlight, and add sticky notes.',
    icon: 'Pencil',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 40,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Supports browser overlay annotations, drawings, and shapes flattened onto the document. Does not alter underlying reflowable text.',
    privacyNote: 'Client-side canvas editing.',
    seoTitle: 'Edit PDF Online — Add Text, Annotate and Draw on PDF Free',
    seoDescription: 'Annotate, draw, highlight, and add text to your PDF documents with an easy browser editor.',
    tags: ['edit', 'annotate', 'draw', 'highlight', 'text', 'pdf'],
  },
  {
    id: 'watermark-pdf',
    slug: 'watermark',
    name: 'Watermark PDF',
    category: 'editing',
    description: 'Add custom text (e.g. "CONFIDENTIAL", "DRAFT") or logo image watermarks with adjustable opacity and rotation.',
    icon: 'Stamp',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Customizable opacity (10%-100%), 45° diagonal or horizontal rotation, font sizing, and page selection.',
    privacyNote: 'Embedded directly in browser memory.',
    seoTitle: 'Watermark PDF Online — Add Text or Image Watermark Free',
    seoDescription: 'Apply secure text or logo watermarks to PDF pages with custom transparency and rotation.',
    tags: ['watermark', 'stamp', 'confidential', 'draft', 'pdf'],
  },
  {
    id: 'sign-pdf',
    slug: 'sign',
    name: 'Sign PDF',
    category: 'editing',
    description: 'Draw your signature, type a stylized script, or upload an image stamp to sign assignments and forms.',
    icon: 'PenTool',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Creates an electronic visual signature overlay on designated pages. This is not a cryptographic X.509 digital certificate.',
    privacyNote: 'Signatures are drawn in your browser and never sent to a server.',
    seoTitle: 'Sign PDF Online Free — Add Signature to PDF | StudentAI',
    seoDescription: 'Draw, type, or upload your signature and place it anywhere on your PDF documents for free.',
    tags: ['sign', 'signature', 'draw', 'stamp', 'contract', 'pdf'],
  },
  {
    id: 'crop-pdf',
    slug: 'crop',
    name: 'Crop PDF',
    category: 'editing',
    description: 'Trim unwanted white margins or crop pages to specific dimensions across single or all pages.',
    icon: 'Crop',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Adjusts the PDF CropBox and MediaBox dimensions.',
    privacyNote: '100% client-side.',
    seoTitle: 'Crop PDF Online — Trim PDF Margins Free | StudentAI',
    seoDescription: 'Crop PDF margins and adjust page dimensions online with instant live preview.',
    tags: ['crop', 'margins', 'trim', 'dimensions', 'pdf'],
  },
  {
    id: 'redact-pdf',
    slug: 'redact',
    name: 'Redact PDF',
    category: 'editing',
    description: 'Permanently remove and black out sensitive data, roll numbers, or personal details with genuine text erasure.',
    icon: 'EyeOff',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    badge: 'Verified',
    limitations: 'Flattens and erases underlying text streams beneath opaque redaction bounds so content cannot be highlighted or extracted.',
    privacyNote: 'Sensitive information is permanently stripped locally on your computer.',
    seoTitle: 'Redact PDF Online — Permanently Remove Sensitive Text Free',
    seoDescription: 'Permanently erase and black out private information from PDF files with true text removal.',
    tags: ['redact', 'blackout', 'privacy', 'censor', 'erase', 'pdf'],
  },
  {
    id: 'pdf-forms',
    slug: 'forms',
    name: 'PDF Forms',
    category: 'editing',
    description: 'Fill out interactive PDF forms, type into form fields, toggle checkboxes, and export completed documents.',
    icon: 'CheckSquare',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Supports standard AcroForm text fields and checkboxes. Flattened appearance streams are updated upon export.',
    privacyNote: 'Form data is kept in browser memory.',
    seoTitle: 'Fill PDF Forms Online Free | StudentAI',
    seoDescription: 'Fill out interactive PDF forms and sign applications online without printing.',
    tags: ['forms', 'fill', 'acroform', 'checkbox', 'fields', 'pdf'],
  },

  // 4. PDF Optimization (2 tools)
  {
    id: 'compress-pdf',
    slug: 'compress',
    name: 'Compress PDF',
    category: 'optimization',
    description: 'Reduce PDF file size by stripping redundant objects and re-encoding streams with honest byte savings metrics.',
    icon: 'Minimize2',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Calculates exact before/after byte differences. If the output cannot be reduced, the user is honestly notified.',
    privacyNote: 'Compression executes in browser memory without server uploads.',
    seoTitle: 'Compress PDF Online — Reduce PDF File Size Free | StudentAI',
    seoDescription: 'Compress PDF files to reduce size for email or submission portals while preserving clarity.',
    tags: ['compress', 'reduce size', 'optimize', 'shrink', 'pdf'],
  },
  {
    id: 'repair-pdf',
    slug: 'repair',
    name: 'Repair PDF',
    category: 'optimization',
    description: 'Attempt structural recovery of damaged or unreadable PDF files by rebuilding corrupted xref tables.',
    icon: 'Wrench',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'Reconstructs document catalog dictionaries and xref tables for damaged headers. Severe byte truncation or zeroed files cannot be recovered.',
    privacyNote: 'Processed locally in browser.',
    seoTitle: 'Repair PDF Online — Fix Corrupted PDF Files Free | StudentAI',
    seoDescription: 'Attempt to recover and repair damaged or corrupted PDF documents safely in your browser.',
    tags: ['repair', 'fix', 'corrupted', 'recover', 'damaged', 'pdf'],
  },

  // 5. PDF Security (3 tools)
  {
    id: 'protect-pdf',
    slug: 'protect',
    name: 'Protect PDF',
    category: 'security',
    description: 'Lock your PDF document with a password to restrict unauthorized viewing and distribution.',
    icon: 'Lock',
    status: 'LIMITED',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 40,
    requiresAI: false,
    requiresServer: false,
    badge: 'Limited',
    limitations: 'Applies password protection. If browser cryptography is restricted on certain documents, user is notified cleanly.',
    privacyNote: 'Passwords are never sent to a server or stored in telemetry.',
    seoTitle: 'Protect PDF Online — Password Protect PDF Free | StudentAI',
    seoDescription: 'Encrypt and password protect your PDF files securely right in your browser.',
    tags: ['protect', 'password', 'encrypt', 'security', 'lock', 'pdf'],
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock',
    name: 'Unlock PDF',
    category: 'security',
    description: 'Remove password restrictions from your PDF document by providing the legitimate authorization password.',
    icon: 'Unlock',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Requires the user to supply the valid password. Does not perform illegal password cracking or brute forcing.',
    privacyNote: 'Decrypted locally in browser memory.',
    seoTitle: 'Unlock PDF Online — Remove PDF Password Free | StudentAI',
    seoDescription: 'Unlock password-protected PDF files with your known password and save an unencrypted copy.',
    tags: ['unlock', 'decrypt', 'remove password', 'security', 'pdf'],
  },
  {
    id: 'compare-pdf',
    slug: 'compare',
    name: 'Compare PDF',
    category: 'security',
    description: 'Upload two versions of a PDF document to inspect text differences, additions, deletions, and structural changes side-by-side.',
    icon: 'GitCompare',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_COMPARE_PAGES,
    requiresAI: false,
    requiresServer: false,
    limitations: 'Compares text streams and page counts side-by-side with color-coded diff highlights.',
    privacyNote: 'Both files are compared locally in browser memory.',
    seoTitle: 'Compare PDF Online — Find Differences Between Two PDFs Free',
    seoDescription: 'Compare two PDF documents side-by-side to highlight text changes, additions, and deletions.',
    tags: ['compare', 'diff', 'versions', 'revisions', 'check', 'pdf'],
  },

  // 6. Scanning & OCR (2 tools)
  {
    id: 'scan-to-pdf',
    slug: 'scan-to-pdf',
    name: 'Scan to PDF',
    category: 'scanning',
    description: 'Use your smartphone or webcam to scan physical documents, apply contrast filters, and create a crisp PDF.',
    icon: 'Camera',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['image/*', 'video/*'],
    supportedOutputTypes: ['.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_IMAGE_SIZE_MB,
    maxPages: 30,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Mobile First',
    limitations: 'Utilizes HTML5 MediaDevices API with grayscale and high-contrast B&W document enhancements.',
    privacyNote: 'Camera feed stays on your device. Zero cloud uploads.',
    seoTitle: 'Scan to PDF Online — Mobile Document Scanner Free | StudentAI',
    seoDescription: 'Scan physical papers and notes using your phone camera and save them directly as a clean PDF.',
    tags: ['scan', 'camera', 'scanner', 'mobile', 'document', 'pdf'],
  },
  {
    id: 'ocr-pdf',
    slug: 'ocr',
    name: 'OCR PDF',
    category: 'scanning',
    description: 'Extract editable text from scanned or image-only PDF documents using client-side optical character recognition.',
    icon: 'ScanText',
    status: 'READY',
    processingMode: 'client',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: PDF_CONFIG.MAX_OCR_PAGES,
    requiresAI: false,
    requiresServer: false,
    isPopular: true,
    badge: 'Popular',
    limitations: 'Renders pages sequentially to canvas and runs Tesseract.js in a Web Worker. Up to 15 pages per batch to preserve memory.',
    privacyNote: '100% private. OCR runs on your local CPU via WebAssembly.',
    seoTitle: 'OCR PDF Online — Extract Text from Scanned PDF Free | StudentAI',
    seoDescription: 'Extract editable text from scanned PDF documents right in your browser using optical character recognition.',
    tags: ['ocr', 'scanned', 'text extraction', 'tesseract', 'recognize', 'pdf'],
  },

  // 7. AI PDF (3 tools)
  {
    id: 'ai-summarize-pdf',
    slug: 'summarize',
    name: 'AI PDF Summarizer',
    category: 'ai',
    description: 'Generate concise executive summaries, detailed study notes, exam questions, and key definitions from your PDF.',
    icon: 'Bot',
    status: 'READY',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/markdown', 'text/plain'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 50,
    requiresAI: true,
    requiresServer: true,
    isPopular: true,
    badge: 'AI Powered',
    limitations: 'Extracts text client-side and transmits up to 30,000 characters to the StudentAI AI gateway. Respects the Global AI kill switch.',
    privacyNote: 'Only extracted document text is sent to the AI gateway for synthesis. Raw PDF is never uploaded.',
    seoTitle: 'AI PDF Summarizer — Summarize PDF Documents Free | StudentAI',
    seoDescription: 'Summarize textbooks, research papers, and lecture notes with AI. Get key points, study notes, and exam prep.',
    tags: ['ai', 'summarize', 'study notes', 'exam questions', 'assistant', 'pdf'],
  },
  {
    id: 'translate-pdf',
    slug: 'translate',
    name: 'Translate PDF',
    category: 'ai',
    description: 'Translate foreign language PDF papers and documents into English, Spanish, French, German, Hindi, and more.',
    icon: 'Languages',
    status: 'READY',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['text/plain', '.pdf'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 30,
    requiresAI: true,
    requiresServer: true,
    badge: 'AI Powered',
    limitations: 'Translates extracted text sections via the AI gateway. Original complex graphic layouts are rendered into clean translated documents.',
    privacyNote: 'Sends extracted text to the AI gateway. Subject to the Global AI kill switch.',
    seoTitle: 'Translate PDF Online — Free AI Document Translator | StudentAI',
    seoDescription: 'Translate academic papers and PDFs into multiple languages accurately with AI.',
    tags: ['translate', 'languages', 'multilingual', 'ai', 'pdf'],
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    name: 'PDF → Markdown',
    category: 'ai',
    description: 'Convert PDF documents into clean, structured Markdown (.md) with headings, bullet points, tables, and code blocks.',
    icon: 'FileCode2',
    status: 'READY',
    processingMode: 'hybrid',
    supportedInputTypes: ['.pdf', 'application/pdf'],
    supportedOutputTypes: ['.md', 'text/markdown'],
    maxFileSizeMB: PDF_CONFIG.MAX_FILE_SIZE_MB,
    maxPages: 40,
    requiresAI: true,
    requiresServer: true,
    badge: 'AI Powered',
    limitations: 'Extracts text structure and leverages AI synthesis for headings, tables, and formatting. Download as .md or copy directly.',
    privacyNote: 'Text structure is processed via the AI gateway.',
    seoTitle: 'PDF to Markdown Converter — Convert PDF to MD Online Free',
    seoDescription: 'Convert PDF documents into formatted Markdown files with preserved headings, lists, and tables.',
    tags: ['markdown', 'md', 'convert', 'notes', 'obsidian', 'notion', 'pdf'],
  },
];

/**
 * Retrieves a PDF tool definition by its unique slug.
 */
export function getPdfToolBySlug(slug: string): PdfToolDefinition | undefined {
  return PDF_TOOLS_REGISTRY.find((t) => t.slug === slug);
}

/**
 * Returns all valid PDF tool slugs.
 */
export function getAllPdfToolSlugs(): string[] {
  return PDF_TOOLS_REGISTRY.map((t) => t.slug);
}

/**
 * Returns PDF tools filtered by category.
 */
export function getPdfToolsByCategory(category: PdfToolCategory): PdfToolDefinition[] {
  return PDF_TOOLS_REGISTRY.filter((t) => t.category === category);
}
