'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { ToolLayout } from '../ToolLayout';
import { getToolBySlug } from '@/lib/tools-registry';
import {
  INTERVIEW_QUESTIONS,
  InterviewQuestion,
} from '@/data/interview-questions-data';
import {
  HelpCircle,
  Eye,
  EyeOff,
  CheckCircle2,
  Clock,
  Shuffle,
  Search,
  BookOpen,
  Sparkles,
  RotateCcw,
} from 'lucide-react';
import { getStorageItem, setStorageItem, STORAGE_KEYS } from '@/lib/storage';

export function InterviewQuestionBank() {
  const tool = getToolBySlug('interview-questions')!;

  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [selectedDifficulty, setSelectedDifficulty] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');

  // Map of question ID to progress status: 'mastered' | 'practice'
  const [progress, setProgress] = useState<Record<string, 'mastered' | 'practice'>>({});
  // Set of revealed question IDs
  const [revealedIds, setRevealedIds] = useState<Set<string>>(new Set());

  useEffect(() => {
    const saved = getStorageItem<Record<string, 'mastered' | 'practice'>>(
      STORAGE_KEYS.INTERVIEW_PROGRESS,
      {}
    );
    if (saved && typeof saved === 'object') {
      setProgress(saved);
    }
  }, []);

  const persistProgress = (updated: Record<string, 'mastered' | 'practice'>) => {
    setProgress(updated);
    setStorageItem(STORAGE_KEYS.INTERVIEW_PROGRESS, updated);
  };

  const toggleReveal = (id: string) => {
    setRevealedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const markStatus = (id: string, status: 'mastered' | 'practice') => {
    const next = { ...progress };
    if (next[id] === status) {
      delete next[id]; // Toggle off if clicked again
    } else {
      next[id] = status;
    }
    persistProgress(next);
  };

  const handleRandomQuestion = () => {
    const unmastered = INTERVIEW_QUESTIONS.filter((q) => progress[q.id] !== 'mastered');
    const pool = unmastered.length > 0 ? unmastered : INTERVIEW_QUESTIONS;
    const rand = pool[Math.floor(Math.random() * pool.length)];
    setSearchQuery(rand.question.slice(0, 20));
    setRevealedIds(new Set([rand.id]));
  };

  const handleReset = () => {
    persistProgress({});
    setRevealedIds(new Set());
    setSearchQuery('');
    setSelectedCategory('all');
    setSelectedDifficulty('all');
  };

  const categories = [
    'all',
    'Python',
    'SQL',
    'Web Development',
    'AI/ML',
    'Cybersecurity',
    'SOC Analyst',
    'Networking',
    'Linux',
    'HR & Behavioral',
  ];

  const filteredQuestions = useMemo(() => {
    return INTERVIEW_QUESTIONS.filter((q) => {
      const matchesCat = selectedCategory === 'all' || q.category === selectedCategory;
      const matchesDiff =
        selectedDifficulty === 'all' || q.difficulty.toLowerCase() === selectedDifficulty.toLowerCase();
      const matchesSearch =
        searchQuery.trim() === '' ||
        q.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
        q.modelAnswer.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCat && matchesDiff && matchesSearch;
    });
  }, [selectedCategory, selectedDifficulty, searchQuery]);

  const masteredCount = Object.values(progress).filter((s) => s === 'mastered').length;
  const practiceCount = Object.values(progress).filter((s) => s === 'practice').length;
  const masteredPercent = Math.round((masteredCount / INTERVIEW_QUESTIONS.length) * 100);

  return (
    <ToolLayout
      tool={tool}
      onReset={handleReset}
      educationalContent={{
        howItWorks: [
          'Practice 50+ curated technical and behavioral interview questions across 9 essential domains.',
          'Test yourself before revealing the model answer and key takeaway bullet points.',
          'Track questions you have mastered versus those that need revision. Stored locally in your browser.',
        ],
        faqs: [
          {
            q: 'Are answers generated by AI on the fly?',
            a: 'No. Every question, model answer, and key takeaway is deterministically curated from standard industry hiring benchmarks.',
          },
        ],
      }}
    >
      <div className="space-y-6 max-w-5xl mx-auto">
        {/* Progress Tracker Card */}
        <div className="p-6 sm:p-8 rounded-3xl border border-indigo-200 dark:border-indigo-900/60 bg-gradient-to-br from-indigo-500/5 via-white to-white dark:from-indigo-950/20 dark:via-slate-900 dark:to-slate-900 shadow-sm space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <span className="text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
                Interview Preparation Progress
              </span>
              <h3 className="text-xl font-extrabold text-slate-900 dark:text-white mt-1">
                {masteredCount} of {INTERVIEW_QUESTIONS.length} Questions Mastered ({masteredPercent}%)
              </h3>
            </div>

            <button
              type="button"
              onClick={handleRandomQuestion}
              className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-semibold hover:bg-indigo-700 transition-colors shadow-sm"
            >
              <Shuffle className="w-4 h-4" />
              <span>Surprise Random Question</span>
            </button>
          </div>

          {/* Progress Bar */}
          <div className="space-y-1.5 pt-1">
            <div className="h-2.5 w-full rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden flex">
              <div
                className="h-full bg-emerald-500 transition-all duration-300"
                style={{ width: `${(masteredCount / INTERVIEW_QUESTIONS.length) * 100}%` }}
              />
              <div
                className="h-full bg-amber-500 transition-all duration-300"
                style={{ width: `${(practiceCount / INTERVIEW_QUESTIONS.length) * 100}%` }}
              />
            </div>
            <div className="flex items-center gap-4 text-[11px] text-slate-500 pt-1">
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
                <span>Mastered ({masteredCount})</span>
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-amber-500" />
                <span>Needs Practice ({practiceCount})</span>
              </span>
              <span className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-slate-300 dark:bg-slate-700" />
                <span>Unvisited ({INTERVIEW_QUESTIONS.length - masteredCount - practiceCount})</span>
              </span>
            </div>
          </div>
        </div>

        {/* Filter and Search Controls */}
        <div className="space-y-3">
          <div className="flex flex-col sm:flex-row items-center gap-3">
            {/* Search */}
            <div className="relative flex-1 w-full">
              <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                placeholder="Search questions or keywords..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-4 py-2.5 text-xs sm:text-sm rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </div>

            {/* Difficulty Filter */}
            <div className="flex items-center gap-1 w-full sm:w-auto">
              {['all', 'beginner', 'intermediate', 'advanced'].map((diff) => (
                <button
                  key={diff}
                  type="button"
                  onClick={() => setSelectedDifficulty(diff)}
                  className={`flex-1 sm:flex-none px-3 py-2 text-xs font-semibold rounded-xl capitalize transition-colors ${
                    selectedDifficulty === diff
                      ? 'bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900'
                      : 'border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-400'
                  }`}
                >
                  {diff}
                </button>
              ))}
            </div>
          </div>

          {/* Category Scrollable Pills */}
          <div className="flex items-center gap-1.5 overflow-x-auto pb-2">
            {categories.map((cat) => (
              <button
                key={cat}
                type="button"
                onClick={() => setSelectedCategory(cat)}
                className={`px-3 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-colors ${
                  selectedCategory === cat
                    ? 'bg-indigo-600 text-white'
                    : 'border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 text-slate-600 dark:text-slate-400 hover:bg-slate-50'
                }`}
              >
                {cat === 'all' ? 'All Categories' : cat}
              </button>
            ))}
          </div>
        </div>

        {/* Questions List */}
        <div className="space-y-4">
          {filteredQuestions.length > 0 ? (
            filteredQuestions.map((q, idx) => {
              const isRevealed = revealedIds.has(q.id);
              const status = progress[q.id];

              return (
                <div
                  key={q.id}
                  className={`p-6 rounded-3xl border transition-all space-y-4 ${
                    status === 'mastered'
                      ? 'border-emerald-200 dark:border-emerald-950 bg-emerald-50/20 dark:bg-emerald-950/10'
                      : status === 'practice'
                      ? 'border-amber-200 dark:border-amber-950 bg-amber-50/20 dark:bg-amber-950/10'
                      : 'border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/50 shadow-sm'
                  }`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">
                    <div className="space-y-1.5 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-xs font-semibold px-2.5 py-0.5 rounded-md bg-indigo-50 dark:bg-indigo-950/70 text-indigo-700 dark:text-indigo-300">
                          {q.category}
                        </span>
                        <span
                          className={`text-[11px] font-semibold px-2 py-0.5 rounded-md ${
                            q.difficulty === 'Beginner'
                              ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300'
                              : q.difficulty === 'Intermediate'
                              ? 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300'
                              : 'bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300'
                          }`}
                        >
                          {q.difficulty}
                        </span>
                      </div>

                      <h3 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white pt-1">
                        {idx + 1}. {q.question}
                      </h3>
                    </div>

                    {/* Action buttons */}
                    <div className="flex items-center gap-2 shrink-0 pt-2 sm:pt-0">
                      <button
                        type="button"
                        onClick={() => markStatus(q.id, 'mastered')}
                        className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-colors flex items-center gap-1 ${
                          status === 'mastered'
                            ? 'bg-emerald-600 text-white'
                            : 'border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-100'
                        }`}
                        title="Mark as Mastered"
                      >
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        <span>Mastered</span>
                      </button>

                      <button
                        type="button"
                        onClick={() => markStatus(q.id, 'practice')}
                        className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-colors flex items-center gap-1 ${
                          status === 'practice'
                            ? 'bg-amber-600 text-white'
                            : 'border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-100'
                        }`}
                        title="Mark as Needs Practice"
                      >
                        <Clock className="w-3.5 h-3.5" />
                        <span>Practice</span>
                      </button>

                      <button
                        type="button"
                        onClick={() => toggleReveal(q.id)}
                        className="px-3 py-1.5 rounded-xl text-xs font-semibold border border-indigo-200 dark:border-indigo-800 bg-indigo-50/50 dark:bg-indigo-950/40 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-100 transition-colors flex items-center gap-1"
                      >
                        {isRevealed ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                        <span>{isRevealed ? 'Hide' : 'Answer'}</span>
                      </button>
                    </div>
                  </div>

                  {/* Model Answer Drawer */}
                  {isRevealed && (
                    <div className="pt-4 border-t border-slate-100 dark:border-slate-800 space-y-3 animate-in fade-in">
                      <div>
                        <span className="text-xs font-bold uppercase tracking-wider text-slate-500 block mb-1">
                          Model Answer
                        </span>
                        <p className="text-sm text-slate-800 dark:text-slate-200 leading-relaxed font-sans">
                          {q.modelAnswer}
                        </p>
                      </div>

                      {q.keyPoints.length > 0 && (
                        <div className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80">
                          <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 block mb-1.5">
                            Key Takeaways & Checklist
                          </span>
                          <ul className="space-y-1 text-xs text-slate-600 dark:text-slate-400 list-disc list-inside">
                            {q.keyPoints.map((pt, i) => (
                              <li key={i}>{pt}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })
          ) : (
            <div className="p-8 text-center rounded-3xl border border-dashed border-slate-200 dark:border-slate-800 text-slate-500 text-sm">
              No interview questions found matching the selected criteria.
            </div>
          )}
        </div>
      </div>
    </ToolLayout>
  );
}
